CRUD endpoints for users
dmitryzhurkovsky/theater-app pull request #5
Opened 2024-02-19 10:53 UTC by ulyana474

2024-02-19 13:20 UTC, Artur-Leshko commented on backend/migrations/versions/2adc0a8a86c2_change_model_fields.py
Просто на будущее - мы не меняем предыдущим миграции :) НИКОГДА

2024-02-19 13:23 UTC, Artur-Leshko commented on backend/src/core/schemas/user/base.py
> +    theatrical_role: Optional[object]  # need to implement
WTF?
У нас же typing в питоне 10 завезли крутой, зачем это делать?

```suggestion
class UserUpdate(BaseModel):
    first_name: str | None = None
    last_name: str | None = None
    email: str | None = None
    free_dates:list[str] | None = None
    phone_number: str | None = None
    theatrical_role: ТУТ ДОЛЖНА БЫТЬ pydantic модель theatrical_role | None = None
```

2024-02-19 13:29 UTC, Artur-Leshko commented on backend/src/endpoints/v1/users.py
> +    return users_res_test
```suggestion
@router.get("/", summary="get users", response_model=PaginationResponseSchema)
async def users(service: UserService = Depends(user_service_pagination)):
    users_res_test = await service.list_users()

    return users_res_test
```

2024-02-19 13:29 UTC, Artur-Leshko commented on backend/src/endpoints/v1/users.py
> +    return {"data": user}
```suggestion
    return  await service.get_or_404(user_id)
```

2024-02-19 13:32 UTC, Artur-Leshko commented on backend/src/endpoints/v1/users.py
> +        return {"message": "Failed to create user"}
response_model=UserCreateResponseSchema | MessageResponseSchema
У нас вот эта строчка нужна для того чтобы результат который ты возвращаешь из endpointa должно быть или UserCreateResponseSchema или MessageResponseSchema, ты можешь просто вернуть user_obj и у тебя эти схемы обработают твой объект из бд

```suggestion
@router.post("/", status_code=status.HTTP_201_CREATED, response_model=UserCreateResponseSchema | MessageResponseSchema)
async def create_user(user: UserCreateResponseSchema, service: UserService = Depends(get_user_service)):
        return await service.create_user(user)
```

2024-02-19 13:32 UTC, Artur-Leshko commented on backend/src/endpoints/v1/users.py
> +    return {"data": user}
тоже самое, где response_schema? не возвращаем просто объект, используем pydantic

2024-02-19 13:36 UTC, Artur-Leshko commented on backend/src/services/base.py
>          self.session = session
Почему тут может быть None в 9 строке? Зачем это нужно?

2024-02-19 13:38 UTC, Artur-Leshko commented on backend/src/services/base.py
> +        query_parameters = QueryParameters(pagination=pagination)
что тут произошло тоже не очень понял? 
Что если нам фронт отправит page=2, per_page=10 например? Это же не будет работать

2024-02-19 13:40 UTC, Artur-Leshko commented on backend/src/utils/query_builder/request_query_handler.py
> +            data=jsonable_encoder(result.scalars().all()),
для чего это тут нужно? и что оно делает?

2024-02-19 13:41 UTC, Artur-Leshko commented on backend/src/utils/query_builder/request_query_handler.py
>                  "per_page": paginator.per_page,
PaginationMetaSchema для того и называется MetaSchema что в ней META информация содержится
а данные уже будут находится в PaginationResponseSchema уххххх

2024-02-19 13:42 UTC, Artur-Leshko commented on backend/src/endpoints/v1/users.py
> +    return UserService(session=session, config=config)
вынеси это в отдельный файл deps.py чтобы этого не было

или вообще лучше придумать как нибудь generic подход по получению Service-ов

2024-02-19 13:49 UTC, Artur-Leshko requested changes
Исправь плиз

2024-02-26 20:31 UTC, ulyana474 commented on backend/src/utils/query_builder/request_query_handler.py
> +            data=jsonable_encoder(result.scalars().all()),
тут jsonable_encoder решает проблему с сериализацией

2024-04-18 15:31 UTC, Nikiktoss commented on backend/migrations/versions/2adc0a8a86c2_change_model_fields.py
> +    op.add_column("theatrical_roles", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False))
У нас уже есть эта колонка бд, так что из-за этой строчки миграция упадёт, лучше тогда юзать alter_column и там уже указывать новые свойства поля

2024-04-18 15:38 UTC, Nikiktoss commented on backend/migrations/versions/2adc0a8a86c2_change_model_fields.py
> -    op.drop_column("users", "type")
Почему убрала удаление колонки type? Просто в классе модели её нет, а в бд эта колонка есть

2024-04-18 15:47 UTC, Nikiktoss commented on backend/migrations/versions/2adc0a8a86c2_change_model_fields.py
> +    op.add_column("theatrical_roles", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False))
зачем нам name в бд, если в модели это relationship с Event и плюс в бд мы храним уже event_id?

2024-04-18 15:51 UTC, Nikiktoss commented on backend/migrations/versions/2adc0a8a86c2_change_model_fields.py
>      op.drop_table("user_theatrical_role_relationship")
А зачем нам это нужно?) Просто создали таблицу и сразу дропнули. Мб удалить строчки где мы создаём таблицу   "user_theatrical_role_relationships", а потом сразу же её дропаем

2024-04-21 17:48 UTC, ulyana474 commented on backend/migrations/versions/2adc0a8a86c2_change_model_fields.py
>      op.drop_table("user_theatrical_role_relationship")
Тут я прописывала __tablename__ = "user_theatrical_role_relationship"  а по дефолту должен быть user_theatrical_role_relationships, поэтому миграция автоматически так сгенерировалась, при накатывании этой миграции название правильное - думаю надо оставить как есть

2024-04-21 17:52 UTC, ulyana474 commented on backend/migrations/versions/2adc0a8a86c2_change_model_fields.py
> -    op.drop_column("users", "type")
Тут решили заменить type у юзера на 3 отдельных поля - is_admin is_director is_actor. Возможно стоит делать через enum но когда мы с димой обсуждали он сказал вынести в 3 отдельных поля, можно еще подумать как лучше

2024-04-21 18:13 UTC, Nikiktoss commented on backend/migrations/versions/2adc0a8a86c2_change_model_fields.py
> -    op.drop_column("users", "type")
Я понимаю, что мы заменили type на три других поля. Я о том, что ты удалила строчку, которая удаляет поле type, т.е у тебя в таблице users в бд это поле остаётся и ещё плюс три новых колонки. Поэтому удаление поля type надо бы вернуть. Ну или решить что лучше использовать enum или три отдельных поля

2024-05-20 10:22 UTC, closed without merging