Feat/adding crud performance and roles
dmitryzhurkovsky/theater-app pull request #9
Opened 2024-08-08 09:45 UTC by Nikiktoss

- Refactor endpoints for users model
- Add crud endpoints to the performances model
- Add crud endpoints to the performance_roles

2024-08-23 09:06 UTC, dmitryzhurkovsky requested changes

2024-08-23 09:06 UTC, dmitryzhurkovsky commented on backend/migrations/versions/5c387b42a9fc_create_performances_table.py
> +        sa.Column("genre", pg.ARRAY(sa.String()), nullable=False),
Return enum, please. 
Really strange decision)

2024-08-23 09:06 UTC, dmitryzhurkovsky commented on backend/src/core/exceptions/base.py
> +    status_code = status.HTTP_400_BAD_REQUEST
409 Conflict

2024-08-23 09:06 UTC, dmitryzhurkovsky commented on backend/src/core/schemas/performance/base.py
> +    model_config = ConfigDict(from_attributes=True)
Check again

2024-08-23 09:06 UTC, dmitryzhurkovsky commented on backend/src/core/schemas/performance/base.py
> +    performance_roles: List[PerformanceRoleRead] = []
Check maybe None?

2024-08-23 09:06 UTC, dmitryzhurkovsky commented on backend/src/db_managers/base.py
> +            LOG.error(f"Failed to create instance of class {self.model.__name__}. {ex.orig}")
Prettify it. 
As reference only:
@app.exception_handler(IntegrityError)
async def integrity_error(request: Request, exception: IntegrityError) -> JSONResponse:
    """Handle a bad request error"""
    foreign_keys_indvalid = re.findall(r'(\w+_id)', exception.args[0])
    if foreign_keys_indvalid:
        detail = f'The following fields are invalid: {foreign_keys_indvalid}'
    else:
        detail = exception.args[0]

    return JSONResponse(
        status_code=BadRequestError.status_code,
        content={'detail': detail}
    )

2024-08-23 09:06 UTC, dmitryzhurkovsky commented on backend/src/models/events.py
>      performance_id: Mapped[UUID] = mapped_column(ForeignKey("performances.id"), nullable=False)
Build an Index. 
Check if there is need of indexes in other models

2024-08-23 09:06 UTC, dmitryzhurkovsky commented on backend/src/models/performance.py
> +    performance_roles: Mapped[List["PerformanceRole"]] = relationship(back_populates="performance", lazy="selectin")
lazyin is default attribute

2024-08-23 09:09 UTC, dmitryzhurkovsky commented
Add closing db connection when we stop FastApi. You can do it in the shutdown event

2024-08-23 09:10 UTC, dmitryzhurkovsky commented
@Artur-Leshko Need you review 🤡

2024-08-23 13:52 UTC, Artur-Leshko commented on backend/migrations/versions/5c387b42a9fc_create_performances_table.py
> -    drop_enum("genre_type_enum")
👎

2024-08-23 13:52 UTC, Artur-Leshko commented on backend/migrations/versions/6616b8872c4a_create_users_table.py
> +        sa.Column("user_roles", postgresql.ARRAY(sa.String()), nullable=False),
👎

2024-08-23 13:53 UTC, Artur-Leshko commented on backend/migrations/versions/6616b8872c4a_create_users_table.py
> -    drop_enum("user_role_type_enum")
👎

2024-08-23 13:54 UTC, Artur-Leshko commented on backend/src/core/schemas/performance/base.py
> +    performance_roles: List[PerformanceRoleRead] = []
```suggestion
    performance_roles: list[PerformanceRoleRead] = []
```

2024-08-23 13:54 UTC, Artur-Leshko commented on backend/src/core/schemas/performance/base.py
> +from typing import Any, List
remove it

2024-08-23 13:54 UTC, Artur-Leshko commented on backend/src/core/schemas/performance/base.py
> +    genre: List[GenreTypeEnum] | None = None
```suggestion
    genre: list[GenreTypeEnum] | None = None
```

2024-08-23 13:55 UTC, Artur-Leshko commented on backend/src/models/performance.py
> +    genre: Mapped[List[str]] = mapped_column(pg.ARRAY(String), nullable=False)
```suggestion
    genre: Mapped[list[str]] = mapped_column(pg.ARRAY(String), nullable=False)
```

2024-08-23 13:56 UTC, Artur-Leshko commented on backend/src/models/performance.py
> +from typing import TYPE_CHECKING, List
remove it

2024-08-23 13:56 UTC, Artur-Leshko commented on backend/src/models/performance.py
> +    performance_roles: Mapped[List["PerformanceRole"]] = relationship(back_populates="performance", lazy="selectin")
```suggestion
    performance_roles: Mapped[list["PerformanceRole"]] = relationship(back_populates="performance", lazy="selectin")
```

2024-08-23 13:56 UTC, Artur-Leshko commented on backend/src/models/users.py
> +    free_dates: Mapped[List[date]] = mapped_column(pg.ARRAY(Date))
```suggestion
    free_dates: Mapped[list[date]] = mapped_column(pg.ARRAY(Date))
```

2024-08-23 14:02 UTC, UladzislauBaranau commented on backend/migrations/versions/5c387b42a9fc_create_performances_table.py
> +        sa.Column("genre", pg.ARRAY(sa.String()), nullable=False),
We can use this [special library](https://github.com/Pogchamp-company/alembic-postgresql-enum) for creating migrations with Enum in further
FYI @dmitryzhurkovsky @Nikiktoss

2024-09-01 16:53 UTC, Nikiktoss commented on backend/src/models/performance.py
> +    performance_roles: Mapped[List["PerformanceRole"]] = relationship(back_populates="performance", lazy="selectin")
lazy="select" is a default value

2024-09-01 17:00 UTC, Nikiktoss commented on backend/src/core/schemas/performance/base.py
> +    performance_roles: List[PerformanceRoleRead] = []
No, if performance has no related roles, performance_roles will be [], because in sqlalchemy model it has type Mapped[list["PerformanceRole"]]

2024-09-01 17:02 UTC, Nikiktoss commented on backend/src/core/schemas/performance/base.py
> +    model_config = ConfigDict(from_attributes=True)
We need it in order to convert sqlalchemy model instance to pydantic model

2024-09-10 19:19 UTC, dmitryzhurkovsky commented on backend/migrations/versions/5c387b42a9fc_create_performances_table.py
> +        sa.Column("genre", pg.ARRAY(sa.String()), nullable=False),
Is there is an opportunity to add it, let's do it. 
I also think about migrations that is used a datestamp as revesion_id. 
We can change env.py

2024-11-26 09:45 UTC, dmitryzhurkovsky approved these changes
Fix comments

2024-11-26 09:45 UTC, dmitryzhurkovsky commented on backend/src/core/deps.py
> +    user: UserUpdate,
??? Maybe shouldn't be there

2024-11-26 09:45 UTC, dmitryzhurkovsky commented on backend/src/core/schemas/performance/base.py
> +    model_config = ConfigDict(from_attributes=True)
Move to read schema

2024-11-26 09:45 UTC, dmitryzhurkovsky commented on backend/src/endpoints/v1/performance.py
> +    dependencies=[Depends(required_roles([UserRoleTypeEnum.ADMIN, UserRoleTypeEnum.SUPER_ADMIN]))],
Remove depends

2024-11-26 09:45 UTC, dmitryzhurkovsky commented on backend/src/models/users.py
> +    def has_a_role(self, roles: list[UserRoleTypeEnum]) -> bool:
rename. has_at_least_one or better name. It's for you decision

2024-11-27 17:26 UTC, merged